# Generated by Django 5.1.1 on 2024-09-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProducto',
            fields=[
                ('id_calificacionProduc', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_productos', to='ModeloGreenMarket.user')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='ModeloGreenMarket.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionProveedor',
            fields=[
                ('id_calificacionProve', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_proveedor', to='ModeloGreenMarket.user')),
                ('id_proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='ModeloGreenMarket.proveedor')),
            ],
        ),
    ]
