# Generated by Django 5.1.1 on 2024-09-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0002_calificacionproducto_calificacionproveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='user',
        ),
    ]
